### ISSUE TITLE
New repo for the list

### ISSUE THREAD

**Issue by Garrettlynch** [jeffThompson/Repo-As-Artwork#3]
I've added another called, Neural CA Kunstformen, to the list on the clone here: https://github.com/Garrettlynch/Repo-As-Artwork-1

**Comment by jeffThompson** [comment]
Ok super! I see you have quite a few projects in your fork that aren't in mine – would you mind submitting a PR so we can merge the branches? Seems like it would make the most sense for this list to be singular, rather than spread across multiple repos.
